name: Tests
on:
  pull_request:
    branches: 
      - '!master'
      - '!develop'
      - '*'
      - '!deploy-docker'

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://npm.pkg.github.com/'
        cache: 'yarn'

    - name: Ensure access
      run: npm whoami --registry https://npm.pkg.github.com/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Config git user
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Install dependencies.
      run: yarn install --immutable

    - name: Lint
      run: yarn run lint

    - name: Tests
      run: yarn run test

    - name: Build
      run: yarn run build