module.exports = {
  bugs: require('./bugs'),
  configuration: require('./configuration'),
  devOps: require('./dev-ops'),
  diff: require('./diff'),
  documentation: require('./documentation'),
  git: require('./git'),
  globalScripts: require('./global-scripts'),
  jsonFormatter: require('./json-formatter'),
  jwt: require('./jwt'),
  logs: require('./logs'),
  mongo: require('./mongo'),
  nodeRepl: require('./node-repl'),
  npm: require('./npm'),
  openai: require('./openai'),
  regex: require('./regex'),
  toolbox: require('./toolbox'),
  uuid: require('./uuid'),
  github: require('./github'),
}