module.exports = {
  bugs: require('@clabroche/modules-bugs'),
  configuration: require('@clabroche/modules-configuration'),
  devOps: require('@clabroche/modules-dev-ops'),
  diff: require('@clabroche/modules-diff'),
  documentation: require('@clabroche/modules-documentation'),
  finder: require('@clabroche/modules-finder'),
  git: require('@clabroche/modules-git'),
  github: require('@clabroche/modules-github'),
  globalScripts: require('@clabroche/modules-global-scripts'),
  jsonFormatter: require('@clabroche/modules-json-formatter'),
  jwt: require('@clabroche/modules-jwt'),
  kanban: require('@clabroche/modules-kanban'),
  logs: require('@clabroche/modules-logs'),
  mongo: require('@clabroche/modules-mongo'),
  nodeRepl: require('@clabroche/modules-node-repl'),
  npm: require('@clabroche/modules-npm'),
  openai: require('@clabroche/modules-openai'),
  regex: require('@clabroche/modules-regex'),
  toolbox: require('@clabroche/modules-toolbox'),
  uuid: require('@clabroche/modules-uuid'),
}