module.exports = {
  bugs: require('@clabroche/modules-bugs-backend'),
  configuration: require('@clabroche/modules-configuration-backend'),
  devOps: require('@clabroche/modules-dev-ops-backend'),
  diff: require('@clabroche/modules-diff-backend'),
  documentation: require('@clabroche/modules-documentation-backend'),
  finder: require('@clabroche/modules-finder-backend'),
  git: require('@clabroche/modules-git-backend'),
  github: require('@clabroche/modules-github-backend'),
  globalScripts: require('@clabroche/modules-global-scripts-backend'),
  jsonFormatter: require('@clabroche/modules-json-formatter-backend'),
  jwt: require('@clabroche/modules-jwt-backend'),
  kanban: require('@clabroche/modules-kanban-backend'),
  logs: require('@clabroche/modules-logs-backend'),
  mongo: require('@clabroche/modules-mongo-backend'),
  nodeRepl: require('@clabroche/modules-node-repl-backend'),
  npm: require('@clabroche/modules-npm-backend'),
  openai: require('@clabroche/modules-openai-backend'),
  regex: require('@clabroche/modules-regex-backend'),
  toolbox: require('@clabroche/modules-toolbox-backend'),
  uuid: require('@clabroche/modules-uuid-backend'),
};
