module.exports = {
  bugs: require('../../bugs/backend'),
  configuration: require('../../configuration/backend'),
  devOps: require('../../dev-ops/backend'),
  diff: require('../../diff/backend'),
  documentation: require('../../documentation/backend'),
  finder: require('../../finder/backend'),
  git: require('../../git/backend'),
  github: require('../../github/backend'),
  globalScripts: require('../../global-scripts/backend'),
  jsonFormatter: require('../../json-formatter/backend'),
  jwt: require('../../jwt/backend'),
  kanban: require('../../kanban/backend'),
  logs: require('../../logs/backend'),
  mongo: require('../../mongo/backend'),
  nodeRepl: require('../../node-repl/backend'),
  npm: require('../../npm/backend'),
  openai: require('../../openai/backend'),
  regex: require('../../regex/backend'),
  toolbox: require('../../toolbox/backend'),
  uuid: require('../../uuid/backend'),
};
